version: '3'
networks:
  ProductNetwork:
    name: ProductNetwork
    driver: bridge
services:
  product-service-gateway:
    image: product-service-gateway
    ports:
    - 5000:5000
    links:
    - eureka-server
    - product-service
    - category-service
    - inventory-service
    networks:
    - ProductNetwork
  eureka-server:
    image: eureka
    ports:
    - 7001:7001
    networks:
    - ProductNetwork
  product-service:
    depends_on:
    - mongodb
    image: product-service
    ports:
    - 5001:5001
    links:
    - eureka-server
    - mongodb
    - category-service
    - inventory-service
    networks:
    - ProductNetwork
  category-service:
    depends_on:
    - mysql-standalone
    image: product-category-service
    ports:
    - 5002:5002
    links:
    - eureka-server
    - mysql-standalone
    networks:
    - ProductNetwork
  inventory-service:
    depends_on:
    - mysql-standalone
    image: product-inventory-service
    ports:
    - 5003:5003
    links:
    - eureka-server
    - mysql-standalone
    networks:
    - ProductNetwork
  mongodb:
    image: mongo
    ports:
    - 27018:27017
    networks:
    - ProductNetwork
  mysql-standalone:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_DATABASE: product
      MYSQL_PASSWORD: root
    ports:
    - 3308:3306
    networks:
    - ProductNetwork