spring:
  application:
    name: Product-Inventotary-Service

server:
  port: 5003
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:7001/eureka