spring:
  application:
    name: Product-Service
  data:
    mongodb:
      database: products
      host: mongo-service

server:
  port: 5001
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:7001/eureka