spring:
  application:
    name: Product-Service
  data:
    mongodb:
      database: products
      host: localhost
      port: 27017
server:
  port: 5001
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka