spring:
  application:
    name: Product-Category-Service
  datasource:
    url: jdbc:mysql://localhost:3306/product?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialact : org.hibernate.dialect.MySQL5Dialect
    
server:
  port: 5002
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka